const express = require('express')
const swaggerUi = require('swagger-ui-express')

const router = express.Router()

const categoriesRoutes = require('./categories')
const testimonialsRoutes = require('./testimonials')
const organizationRoutes = require('./organizations')
const membersRoute = require('./members')
const commentsRoutes = require('./comments')
const slidesRoute = require('./slides')
const activitiesRoute = require('./activities')
const contactsRoute = require('./contacts')
const backofficeRoute = require('./backoffice')
const newsRoutes = require('./news')
const authRoutes = require('./auth')
const usersRoute = require('./users')
const docs = require('../docs')

router.use('/api/docs', swaggerUi.serve)
router.get('/api/docs', swaggerUi.setup(docs))
router.use('/categories', categoriesRoutes)
router.use('/organizations', organizationRoutes)
router.use('/testimonials', testimonialsRoutes)
router.use('/members', membersRoute)
router.use('/comments', commentsRoutes)
router.use('/slides', slidesRoute)
router.use('/activities', activitiesRoute)
router.use('/contacts', contactsRoute)
router.use('/backoffice', backofficeRoute)
router.use('/news', newsRoutes)
router.use('/auth', authRoutes)
router.use('/users', usersRoute)

module.exports = router
